### ISSUE TITLE
QWebview doesn't display JPEG on Windows/Webkit TP5/Qt5.6.2

### ISSUE THREAD

**Issue by NiHoT** [Vitallium/qtwebkit-libs-win#1]
Hi, after building Wekbit TP5 on windows with Qt5.6.2 and install it, I tried a quick test and I notice that JPEG img are not rendered in QWebView. Maybe a deployment issue? (PNG are ok!)

(From : https://github.com/annulen/webkit/issues/499)

**Comment by vitallium** [comment]
Fixed
